spring.application.name=demo
spring.config.import=file:/home/rembrandt/.env[.properties]

spring.datasource.url=jdbc:mariadb://${db_location}/phoenix_web
spring.datasource.username=${db_user}
spring.datasource.password=${db_pswd}

server.port=9000
server.address=0.0.0.0
spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=40MB
logging.level.org.springframework.security=DEBUG