spring.application.name=demo
#spring.datasource.url=jdbc:mariadb://192.168.0.176:3306/phoenix_web
#spring.datasource.url=jdbc:mariadb://192.168.123.189:3306/phoenix_web
spring.datasource.url=jdbc:mariadb://192.168.123.214:3306/phoenix_web

spring.datasource.username=remote_user
spring.datasource.password=pstv1688
server.port=9000
server.address=0.0.0.0
# Max size allowed for a single file
spring.servlet.multipart.max-file-size=40MB

# Max size allowed for the entire multipart/form-data request
spring.servlet.multipart.max-request-size=40MB
logging.level.org.springframework.security=DEBUG