spring.application.name=demo1
spring.datasource.url=jdbc:mariadb://localhost:3306/phoenix_web
spring.datasource.username=root
spring.datasource.password=pstv168;
server.port=58000
app.base-url=http://168.148.64.115
app.editorial-zone=America/Los_Angeles