spring.application.name=demo1
spring.config.import=file:/home/rembrandt/.env[.properties]

spring.datasource.url=jdbc:mariadb://${db_location}/phoenix_web
spring.datasource.username=${db_user}
spring.datasource.password=${db_pswd}

server.port=58000
server.address=127.0.0.1
server.forward-headers-strategy=NATIVE

app.base-url=${web_deployment}
app.editorial-zone=America/Los_Angeles
