spring.application.name=demo1
#spring.datasource.url=jdbc:mariadb://192.168.123.72:3306/phoenix_web
#spring.datasource.url=jdbc:mariadb://192.168.0.176:3306/phoenix_web
spring.datasource.url=jdbc:mariadb://192.168.123.189:3306/phoenix_web
spring.datasource.username=remote_user
spring.datasource.password=pstv1688
server.port=58000